/**
 * 
 * @param {Object} - info object generated by graphQL and passed as a 3rd argument to resolver functions.
 * @returns {Array} - returns array of strings that reprsent fields requested by graphQL client
 */
const retrieveFields = info => info.fieldNodes[0].selectionSet.selections.map(el => el.name.value);

module.exports = {
    retrieveFields
};