const knex = require('../../db/knex');
const { calcLimitOffset } = require('../../helpers/calcLimitOffset');
const { transformFdaStatus } = require('../../helpers/dataHelpers');
const { retrieveFields } = require('../../helpers/queryHelpers');

/**
 * @param {Array} data
 * @returns {Array} - Returns a transformed array of objects.
 */
const transformGeneDrugs = data => {
    return data.map(gene_drug => {
        const {
            id,
            drug_id,
            estimate,
            se,
            n,
            tstat,
            fstat,
            pvalue,
            df,
            fdr,
            FWER_genes,
            FWER_drugs,
            FWER_all,
            BF_p_all,
            mDataType,
            level,
            drug_like_molecule,
            in_clinical_trials,
            dataset_id,
            dataset_name,
            drug_name,
            smiles,
            inchikey,
            pubchem,
            fda_status,
            tissue_id,
            tissue_name,
            gene_id,
            gene_name,
            ensg,
            gene_seq_start,
            gene_seq_end
        } = gene_drug;
        return {
            id,
            estimate,
            se,
            n,
            tstat,
            fstat,
            pvalue,
            df,
            fdr,
            FWER_genes,
            FWER_drugs,
            FWER_all,
            BF_p_all,
            mDataType,
            level,
            drug_like_molecule,
            in_clinical_trials,
            gene: {
                id: gene_id,
                name: gene_name,
                annotation: {
                    gene_id,
                    ensg,
                    gene_seq_start,
                    gene_seq_end
                }
            },
            dataset: {
                id: dataset_id,
                name: dataset_name
            },
            compound: {
                id: drug_id,
                name: drug_name,
                annotation: {
                    smiles,
                    inchikey,
                    pubchem,
                    fda_status: transformFdaStatus(fda_status)
                }
            },
            tissue: {
                id: tissue_id,
                name: tissue_name
            },
        };
    });
};

/**
 * Returns the transformed data for all the compounds in the database.
 * @param {Object} args - args object generated by GraphQL client (not used in the function).
 * @param {Object} context - parent object generated by GraphQL client (not used in the function).
 * @param {Object} info - info object generated by GraphQL client, contains data about requested fields.
 * @param {number} [args.geneId = 1] - GeneId for the query.
 * @param {number} [args.compoundId = 1] - CompoundId for the query.
 * @param {number} [args.page = 1] - Current page number.
 * @param {number} [args.per_page = 20] - Total values per page.
 * @param {boolean} [args.all = false] - Boolean value whether to show all the data or not.
 */
const gene_drugs = async (args, context, info) => {
    const { geneId, compoundId, page = 1, per_page = 20, all = false } = args;
    if (!geneId && !compoundId) throw new Error('Ivalid input! Query must include geneId or compoundId'); 
    try {
        const { limit, offset } = calcLimitOffset(page, per_page);
        console.log(info.fieldNodes[0].selectionSet.selections);
        const listOfFields = retrieveFields(info);
        console.log(listOfFields);
        let baseQuery = knex.select('id',
            'gene_name',
            'ensg',
            'gene_seq_start',
            'gene_seq_end',
            'estimate',
            'se',
            'n',
            'tstat',
            'fstat',
            'pvalue',
            'dataset_name',
            'drug_name',
            'smiles',
            'inchikey',
            'pubchem',
            'fda_status',
            'tissue_name',
            'df',
            'fdr',
            'FWER_genes',
            'FWER_drugs',
            'FWER_all',
            'BF_p_all',
            'mDataType',
            'level',
            'drug_like_molecule',
            'in_clinical_trials',
            'datasets.dataset_id as dataset_id',
            'drugs.drug_id as drug_id',
            'tissues.tissue_id as tissue_id',
            'genes.gene_id as gene_id',)
            .from('gene_drugs');

        if (geneId) baseQuery = baseQuery.where({ 'gene_drugs.gene_id': geneId });
        if (compoundId) baseQuery = geneId 
            ? baseQuery.andWhere({ 'gene_drugs.drug_id': compoundId }) 
            : baseQuery.where({ 'gene_drugs.drug_id': compoundId });
        if (!all) baseQuery = baseQuery.limit(limit).offset(offset);

        const geneDrugs = await baseQuery
            .join('datasets', 'datasets.dataset_id', 'gene_drugs.dataset_id')
            .join('drugs', 'drugs.drug_id', 'gene_drugs.drug_id')
            .join('drug_annots', 'drug_annots.drug_id', 'gene_drugs.drug_id')
            .join('tissues', 'tissues.tissue_id', 'gene_drugs.tissue_id')
            .join('genes', 'genes.gene_id', 'gene_drugs.gene_id');
        
        return transformGeneDrugs(geneDrugs);
    } catch (err) {
        console.log(err);
        throw err;
    }
};

module.exports = {
    gene_drugs
};