name: Github Actions

on: 
  push:
    branches: 
      - sandbox-mn

jobs:
  test: 
    name: Server Unit Tests
    runs-on: ubuntu-latest

    strategy:
      matrix: 
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: npm install
      working-directory: server #set server as working dir
    - name: Test
      run: npm test
      working-directory: server #set server as working dir