name: Github Actions

# Define an event (or events) that triggers this workflow.
on:
  push:
    branches: 
      - testing
      - master
  pull_request:
    branches:
      - master
      - development

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Change directory to client
      run: pushd ./client
    - name: Install modules
      run: npm install
    - name: Run tests
      run: npm test
    - name: Pop directory
      run: popd
