name: Github Actions

# Define an event (or events) that triggers this workflow.
on:
  push:
    branches: 
      - testing
      - master
  pull_request:
    branches:
      - master
      - development
defaults:
  run:
    working-directory: client

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install
    - name: Run tests
      run: npm test
