name: Github Actions - frontend testing

on:
  pull_request:
    branches:
      - master
      - development
      
jobs:
  test:
    name: Front-end tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install
    - name: Run tests
      run: npm test
